name: SalesTheory
favicon: null
layout_spectrum: 0.63256
typography_spectrum: 0.45476
title: Practing Sales
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#00ffff'
    - '#ff8300'
    - '#00a3e7'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
