name: SalesTheory
favicon: null
layout_spectrum: 0.56286
typography_spectrum: 0.66911
title: SalesTheory
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#00ffff'
    - '#ff8300'
    - '#00a3e7'
  brandStrength: 0.4375
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
